### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by plscks** [plscks/CharacterPlanner#2]
So this is still under development, it is not perfect by any means in any way. I am working on it as time allows me. Here is a quick little list of things off the top of my head that I will be working to do:

# Immediate TODO list

- [ ] Make a more mobile friendly UI
- [ ] Color scheme
- [ ] Tune back end performance
- [ ] Implement the post-maxx Rank system
- [ ] Toggle for turncoat class T3s for their T2 skills (so you can see what will change to what better)
- [ ] Double and triple check that skills have accurate descriptions

# Further down the line concepts

- [ ] Interaction with Character API to import existing characters in a pre built state or level one state with Ranks already taken into account
- [ ] Character ID specific character lookup direct from planner
